### ISSUE TITLE
MAC addresses for linked sims not being decapped

### ISSUE THREAD

**Issue by carbon43** [DrewLX/EventMasterSimControl#1]
Letters for MAC addresses need to be de-capitalized on output, otherwise linking will not function correctly.

Thank you for putting this app together in Nick's memory

**Comment by DrewLX** [comment]
This was fixed in 0.6

**Comment by carbon43** [comment]
Yep it was. This issue was opened when the app was at 0.5. On GitHub its up to the developer to close the issue once its corrected. Thanks.
